# Flight Benchy run configuration
imu:
  report: game_rotation_vector
  report_hz: 100
pid:
  hz: 50
  kp: 3.5
  ki: 0.4
  kd: 0.3
  integral_limit: 50.0
motor:
  base_throttle: 300
  throttle_min: 70
  throttle_max: 600
encoder:
  axis_center: 422
telemetry:
  sample_every: 10
prediction:
  lead_time_ms: 60
